<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by extdeveval::buildAutoloadRegistry.
// This file was generated on 2009-12-06 13:50

$extensionPath = t3lib_extMgm::extPath('ggspritedgmenu');
return array(
	'tx_ggspritedgmenu_pi1' => $extensionPath . 'pi1/class.tx_ggspritedgmenu_pi1.php',
	'tx_ggspritedgmenu_collector' => $extensionPath . 'res/class.tx_ggspritedgmenu_collector.php',
	'tx_ggspritedgmenu_csstemplate' => $extensionPath . 'res/class.tx_ggspritedgmenu_csstemplate.php',
	'tx_ggspritedgmenu_image' => $extensionPath . 'res/class.tx_ggspritedgmenu_image.php',
	'tx_ggspritedgmenu_styles' => $extensionPath . 'res/class.tx_ggspritedgmenu_styles.php',
	'user_ggspritedgmenu_pagepost' => $extensionPath . 'res/user_ggspritedgmenu_pagepost.php',
);
?>